name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup target add x86_64-pc-windows-gnu
    - name: Setup
      run: rustup toolchain install stable-x86_64-pc-windows-gnu
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target=x86_64-pc-windows-gnu
    - name: Run tests
      run: cargo test --verbose
